// <auto-generated />
using System;
using AlphaZero.Modules.Tenants.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaZero.Modules.Tenants.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908095736_AddTenantBranding")]
    partial class AddTenantBranding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Tenants")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaZero.Modules.Tenants.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Tenants", "Tenants");
                });

            modelBuilder.Entity("AlphaZero.Modules.Tenants.Domain.Tenant", b =>
                {
                    b.OwnsOne("AlphaZero.Modules.Tenants.Domain.TenantBranding", "Branding", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DarkModeLogoUrl")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("DarkModeLogoUrl");

                            b1.Property<string>("FaviconUrl")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("FaviconUrl");

                            b1.Property<string>("LogoUrl")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("LogoUrl");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasDefaultValue("#2563eb")
                                .HasColumnName("PrimaryColor");

                            b1.Property<string>("SecondaryColor")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("SecondaryColor");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants", "Tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Branding")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
