// <auto-generated />
using System;
using AlphaZero.Modules.Identity.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaZero.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416050912_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.ManagedPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Statements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("ManagedPolicies");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrincipalTemplates");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("IdentityId", "TenantId")
                        .IsUnique();

                    b.ToTable("TenantUsers");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUserPrinciaplAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipalTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ResourceArn");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalTemplateId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantUserId", "PrincipalTemplateId", "Resource")
                        .IsUnique();

                    b.ToTable("TenantPrinciaplAssignments");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalPolicyAssignment", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagedPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("PrincipalId", "ManagedPolicyId");

                    b.HasIndex("ManagedPolicyId");

                    b.ToTable("PrincipalManagedPolicyAssignments", (string)null);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Principal", b =>
                {
                    b.HasBaseType("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate");

                    b.Property<string>("InlinePolicies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PrincipalScope")
                        .HasColumnType("text")
                        .HasColumnName("PrincipalScopePattern");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeResourceType")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasIndex("TenantUserId");

                    b.ToTable("Principals");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUserPrinciaplAssignment", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.TenantUser", "TenantUser")
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalPolicyAssignment", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.ManagedPolicy", "ManagedPolicy")
                        .WithMany()
                        .HasForeignKey("ManagedPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedPolicy");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Principal", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate", null)
                        .WithOne()
                        .HasForeignKey("AlphaZero.Modules.Identity.Domain.Models.Principal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
