// <auto-generated />
using System;
using AlphaZero.Modules.Identity.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaZero.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420042915_addedSagaInfo")]
    partial class addedSagaInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.ManagedPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Statements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ManagedPolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "AdministratorAccess",
                            Statements = "[{\"Sid\":\"AllowAll\",\"Actions\":[\"*:*\"],\"Effect\":true}]"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "StudentAccess",
                            Statements = "[{\"Sid\":\"AllowViewCourses\",\"Actions\":[\"courses:View\",\"subjects:List\",\"subjects:View\"],\"Effect\":true},{\"Sid\":\"AllowStreaming\",\"Actions\":[\"video:Stream\"],\"Effect\":true},{\"Sid\":\"AllowCompletion\",\"Actions\":[\"enrollments:Complete\"],\"Effect\":true}]"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "CourseWorkerAccess",
                            Statements = "[{\"Sid\":\"AllowCourseProduction\",\"Actions\":[\"courses:Create\",\"courses:View\",\"courses:Edit\",\"courses:Submit\"],\"Effect\":true},{\"Sid\":\"AllowVideoUpload\",\"Actions\":[\"video:Upload\",\"video:View\",\"video:List\"],\"Effect\":true}]"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "TeacherAccess",
                            Statements = "[{\"Sid\":\"AllowCourseReviewAndEdit\",\"Actions\":[\"courses:View\",\"courses:Edit\",\"courses:Submit\"],\"Effect\":true},{\"Sid\":\"AllowExamManagement\",\"Actions\":[\"exams:Create\",\"exams:Grade\",\"exams:View\"],\"Effect\":true}]"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "CourseManagerAccess",
                            Statements = "[{\"Sid\":\"AllowQAWorkflow\",\"Actions\":[\"courses:View\",\"courses:Approve\",\"courses:Reject\",\"courses:Publish\"],\"Effect\":true}]"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "LibraryManagerAccess",
                            Statements = "[{\"Sid\":\"AllowCodeGeneration\",\"Actions\":[\"library:GenerateCodes\",\"library:SellCodes\",\"library:Audit\"],\"Effect\":true}]"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "LibraryAccountantAccess",
                            Statements = "[{\"Sid\":\"AllowLibraryAudit\",\"Actions\":[\"library:Audit\",\"library:AttachCourses\"],\"Effect\":true}]"
                        });
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrincipalTemplates");

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-100000000001"),
                            Name = "Administrator",
                            PrincipalType = "Role"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-100000000002"),
                            Name = "Student",
                            PrincipalType = "Role"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-100000000003"),
                            Name = "CourseWorker",
                            PrincipalType = "Role"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-100000000004"),
                            Name = "Teacher",
                            PrincipalType = "Role"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-100000000005"),
                            Name = "TenantCourseManager",
                            PrincipalType = "Role"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-100000000006"),
                            Name = "LibraryManager",
                            PrincipalType = "Role"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-100000000007"),
                            Name = "LibraryAccountant",
                            PrincipalType = "Role"
                        });
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("IdentityId", "TenantId")
                        .IsUnique();

                    b.ToTable("TenantUsers");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUserPrinciaplAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipalTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ResourceArn");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalTemplateId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantUserId", "PrincipalTemplateId", "Resource")
                        .IsUnique();

                    b.ToTable("TenantPrinciaplAssignments");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalPolicyAssignment", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagedPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("PrincipalId", "ManagedPolicyId");

                    b.HasIndex("ManagedPolicyId");

                    b.ToTable("PrincipalManagedPolicyAssignments", (string)null);

                    b.HasData(
                        new
                        {
                            PrincipalId = new Guid("00000000-0000-0000-0000-100000000001"),
                            ManagedPolicyId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            PrincipalId = new Guid("00000000-0000-0000-0000-100000000002"),
                            ManagedPolicyId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            PrincipalId = new Guid("00000000-0000-0000-0000-100000000003"),
                            ManagedPolicyId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            PrincipalId = new Guid("00000000-0000-0000-0000-100000000004"),
                            ManagedPolicyId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            PrincipalId = new Guid("00000000-0000-0000-0000-100000000005"),
                            ManagedPolicyId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            PrincipalId = new Guid("00000000-0000-0000-0000-100000000006"),
                            ManagedPolicyId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            PrincipalId = new Guid("00000000-0000-0000-0000-100000000007"),
                            ManagedPolicyId = new Guid("00000000-0000-0000-0000-000000000007")
                        });
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Principal", b =>
                {
                    b.HasBaseType("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate");

                    b.Property<string>("InlinePolicies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalScope")
                        .HasColumnType("text")
                        .HasColumnName("PrincipalScopePattern");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeResourceType")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasIndex("Username", "TenantId")
                        .IsUnique();

                    b.ToTable("Principals");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUserPrinciaplAssignment", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.TenantUser", "TenantUser")
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalPolicyAssignment", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.ManagedPolicy", "ManagedPolicy")
                        .WithMany()
                        .HasForeignKey("ManagedPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedPolicy");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Principal", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.PrincipalTemplate", null)
                        .WithOne()
                        .HasForeignKey("AlphaZero.Modules.Identity.Domain.Models.Principal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
