// <auto-generated />
using System;
using AlphaZero.Modules.Identity.Domain.Models.Principals;
using AlphaZero.Modules.Identity.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaZero.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Principals.Policies.ManagedPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Statements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ManagedPolicies");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastMainDeviceSwitchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MainDeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("IdentityId", "TenantId")
                        .IsUnique();

                    b.ToTable("TenantUsers");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUserPrincipalAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ResourceArn");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantUserId", "PrincipalId", "Resource")
                        .IsUnique();

                    b.ToTable("TenantPrincipalAssignments", (string)null);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantUserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.ConditionDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<IConditionNode>("InnerCondition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Name");

                    b.ToTable("ConditionDefinitions");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InlinePolicies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalScopePattern")
                        .HasColumnType("text");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Username", "TenantId")
                        .IsUnique();

                    b.ToTable("Principals", (string)null);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalPolicyAssignment", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagedPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("PrincipalId", "ManagedPolicyId");

                    b.HasIndex("ManagedPolicyId");

                    b.ToTable("PrincipalManagedPolicyAssignments", (string)null);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUserPrincipalAssignment", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalDataModel", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.TenantUser", "TenantUser")
                        .WithMany()
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenantUser");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.UserDevice", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.TenantUser", null)
                        .WithMany("Devices")
                        .HasForeignKey("TenantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalPolicyAssignment", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.Principals.Policies.ManagedPolicy", "ManagedPolicy")
                        .WithMany()
                        .HasForeignKey("ManagedPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalDataModel", null)
                        .WithMany("PrincipalPolicyAssignments")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedPolicy");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.TenantUser", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalDataModel", b =>
                {
                    b.Navigation("PrincipalPolicyAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
