// <auto-generated />
using System;
using System.Collections.Generic;
using AlphaZero.Modules.Identity.Domain.Models;
using AlphaZero.Modules.Identity.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaZero.Modules.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.ManagedPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<PolicyTemplateStatement>>("Statements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("ManagedPolicies", (string)null);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<IReadOnlyCollection<PolicyStatement>>("Statements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Principal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalScopeUrn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeResourceType")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("ResourceId", "ScopeResourceType");

                    b.ToTable("Principals", (string)null);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalPolicyAssignment", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ManagedPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("PrincipalId", "ManagedPolicyId");

                    b.HasIndex("ManagedPolicyId");

                    b.ToTable("PrincipalPolicyAssignments", (string)null);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Policy", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.Principal", null)
                        .WithMany("InlinePolicies")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Infrastructure.Models.PrincipalPolicyAssignment", b =>
                {
                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.ManagedPolicy", "ManagedPolicy")
                        .WithMany()
                        .HasForeignKey("ManagedPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaZero.Modules.Identity.Domain.Models.Principal", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedPolicy");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("AlphaZero.Modules.Identity.Domain.Models.Principal", b =>
                {
                    b.Navigation("InlinePolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
