<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>AlphaZero.ArchitectureTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\alphazero-api\AlphaZero.Shared\AlphaZero.Shared.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\Courses\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\Courses\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\VideoUploading\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\VideoUploading\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\Assessments\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\Assessments\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\Library\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\Library\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\Tenants\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\src\alphazero-api\Modules\Tenants\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
