// <auto-generated />
using System;
using System.Collections;
using AlphaZero.Modules.Courses.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaZero.Modules.Courses.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Courses")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NextAvailableBitIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OnDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("TenantId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("Courses", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OnDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("TenantId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("CourseSection", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BitIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime?>("OnDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("SectionId");

                    b.HasIndex("TenantId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("CourseSectionItem", "Courses");

                    b.HasDiscriminator<string>("ItemType").HasValue("CourseSectionItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Enrollements.Enrollement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollements", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Subject.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("OnDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("TenantId")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("Subjects", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Infrastructure.Sagas.CourseRedemption.CourseRedemptionState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CourseArn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CorrelationId");

                    b.ToTable("CourseRedemptionStates", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Infrastructure.Sagas.CourseRevocation.CourseRevocationState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("ResourceArn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnauthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CorrelationId");

                    b.ToTable("CourseRevocationStates", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSectionDocument", b =>
                {
                    b.HasBaseType("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSectionItem");

                    b.HasDiscriminator().HasValue("Document");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSectionLesson", b =>
                {
                    b.HasBaseType("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSectionItem");

                    b.HasDiscriminator().HasValue("Lesson");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSectionQuiz", b =>
                {
                    b.HasBaseType("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSectionItem");

                    b.HasDiscriminator().HasValue("Quiz");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSection", b =>
                {
                    b.HasOne("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.Course", null)
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSectionItem", b =>
                {
                    b.HasOne("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSection", null)
                        .WithMany("Items")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Enrollements.Enrollement", b =>
                {
                    b.OwnsOne("AlphaZero.Modules.Courses.Domain.Aggregates.Enrollements.Progress", "Progress", b1 =>
                        {
                            b1.Property<Guid>("EnrollementId")
                                .HasColumnType("uuid");

                            b1.Property<BitArray>("Bitmask")
                                .IsRequired()
                                .HasColumnType("varbit")
                                .HasColumnName("ProgressBitmask");

                            b1.Property<int>("TotalItems")
                                .HasColumnType("integer")
                                .HasColumnName("ProgressTotalItems");

                            b1.HasKey("EnrollementId");

                            b1.ToTable("Enrollements", "Courses");

                            b1.WithOwner()
                                .HasForeignKey("EnrollementId");
                        });

                    b.Navigation("Progress")
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.Course", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSection", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
