// <auto-generated />
using System;
using System.Collections;
using System.Text.Json;
using AlphaZero.Modules.Courses.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaZero.Modules.Courses.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913141335_CourseAssetSourceOfTruth")]
    partial class CourseAssetSourceOfTruth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Courses")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NextAvailableBitIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OnDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("Courses", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceArn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UploadedUtcAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResourceArn")
                        .IsUnique();

                    b.HasIndex("CourseId", "State");

                    b.ToTable("CourseAssets", "Courses");

                    b.HasDiscriminator<string>("AssetType").HasValue("CourseAsset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CoursePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Name")
                        .IsUnique();

                    b.ToTable("CoursePlans", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OnDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("CourseSections", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CurriculumItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BitIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MainType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OnDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("SectionId");

                    b.ToTable("CurriculumItems", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Enrollements.Enrollement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollements", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Subject.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("OnDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("Subjects", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Infrastructure.CourseAnalytics", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemCompletions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("SumOfCompletionPercentages")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalEnrollments")
                        .HasColumnType("integer");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("CourseAnalytics", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Infrastructure.Sagas.CourseRedemption.CourseRedemptionState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CourseArn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CorrelationId");

                    b.ToTable("CourseRedemptionStates", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Infrastructure.Sagas.CourseRevocation.CourseRevocationState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("ResourceArn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UnauthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CorrelationId");

                    b.ToTable("CourseRevocationStates", "Courses");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.AssessmentCourseAsset", b =>
                {
                    b.HasBaseType("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseAsset");

                    b.Property<int>("QuestionsNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasDiscriminator().HasValue("Assessment");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.DocumentCourseAsset", b =>
                {
                    b.HasBaseType("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseAsset");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("Document");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.VideoCourseAsset", b =>
                {
                    b.HasBaseType("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseAsset");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("RelativeStreamingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasDiscriminator().HasValue("Video");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseAsset", b =>
                {
                    b.HasOne("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.Course", null)
                        .WithMany("Assets")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CoursePlan", b =>
                {
                    b.HasOne("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.Course", null)
                        .WithMany("Plans")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSection", b =>
                {
                    b.HasOne("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.Course", null)
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CurriculumItem", b =>
                {
                    b.HasOne("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSection", null)
                        .WithMany("Items")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CurriculumResource", "Resources", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CourseAssetId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CurriculumItemId")
                                .HasColumnType("uuid");

                            b1.Property<JsonElement>("Metadata")
                                .HasColumnType("jsonb");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("CourseAssetId");

                            b1.HasIndex("CurriculumItemId");

                            b1.ToTable("CurriculumResources", "Courses");

                            b1.HasOne("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseAsset", "Asset")
                                .WithMany()
                                .HasForeignKey("CourseAssetId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("CurriculumItemId");

                            b1.Navigation("Asset");
                        });

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Enrollements.Enrollement", b =>
                {
                    b.OwnsOne("AlphaZero.Modules.Courses.Domain.Aggregates.Enrollements.Progress", "Progress", b1 =>
                        {
                            b1.Property<Guid>("EnrollementId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ActiveItems")
                                .HasColumnType("integer")
                                .HasColumnName("ProgressActiveItems");

                            b1.Property<BitArray>("Bitmask")
                                .IsRequired()
                                .HasColumnType("varbit")
                                .HasColumnName("ProgressBitmask");

                            b1.Property<int>("TotalItems")
                                .HasColumnType("integer")
                                .HasColumnName("ProgressTotalItems");

                            b1.HasKey("EnrollementId");

                            b1.ToTable("Enrollements", "Courses");

                            b1.WithOwner()
                                .HasForeignKey("EnrollementId");
                        });

                    b.Navigation("Progress")
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.Course", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Plans");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AlphaZero.Modules.Courses.Domain.Aggregates.Courses.CourseSection", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
