// <auto-generated />
using System;
using AlphaZero.Modules.VideoUploading.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaZero.Modules.VideoUploading.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401111035_RemovedTemp")]
    partial class RemovedTemp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("video_uploading")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaZero.Modules.VideoUploading.Domain.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OutputFolder")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Videos", "video_uploading");
                });

            modelBuilder.Entity("AlphaZero.Modules.VideoUploading.Infrastructure.Sagas.VideoState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("FinalUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("MediaConverterJobId")
                        .HasColumnType("text");

                    b.Property<string>("S3OutputPrefix")
                        .HasColumnType("text");

                    b.Property<int?>("SourceHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceWidth")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.ToTable("VideoState", "video_uploading");
                });

            modelBuilder.Entity("AlphaZero.Modules.VideoUploading.Domain.Models.Video", b =>
                {
                    b.OwnsOne("AlphaZero.Modules.VideoUploading.Domain.Models.VideoMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("VideoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ContentType");

                            b1.Property<long>("FileSize")
                                .HasColumnType("bigint")
                                .HasColumnName("FileSize");

                            b1.Property<string>("OriginalFileName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("OriginalFileName");

                            b1.HasKey("VideoId");

                            b1.ToTable("Videos", "video_uploading");

                            b1.WithOwner()
                                .HasForeignKey("VideoId");
                        });

                    b.OwnsOne("AlphaZero.Modules.VideoUploading.Domain.Models.VideoSpecifications", "Specifications", b1 =>
                        {
                            b1.Property<Guid>("VideoId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval")
                                .HasColumnName("Duration");

                            b1.HasKey("VideoId");

                            b1.ToTable("Videos", "video_uploading");

                            b1.WithOwner()
                                .HasForeignKey("VideoId");

                            b1.OwnsOne("AlphaZero.Modules.VideoUploading.Domain.Models.Resolution", "Resolution", b2 =>
                                {
                                    b2.Property<Guid>("VideoSpecificationsVideoId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("height")
                                        .HasColumnType("integer")
                                        .HasColumnName("Height");

                                    b2.Property<int>("width")
                                        .HasColumnType("integer")
                                        .HasColumnName("Width");

                                    b2.HasKey("VideoSpecificationsVideoId");

                                    b2.ToTable("Videos", "video_uploading");

                                    b2.WithOwner()
                                        .HasForeignKey("VideoSpecificationsVideoId");
                                });

                            b1.Navigation("Resolution")
                                .IsRequired();
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Specifications")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
